exclude: ["Rakefile", "Gemfile", "config.rb", "README.md", "sass"]

pygments: true

# General
title: Sonny T.
description: New York based web junkie. Currently lead developer at StyleCaster Media Group.
url: http://sonnyt.com
github_url: http://sonnyt.github.io
permalink: /:title
pygments: true

# Network usernames
twitter: sonnyt
github_user: sonnyt
linkedin: sonny-tulyaganov/18/964/910
email: hi@sonnyt.com
themeforest: sonnyt