# General
title: Sonny T.
description: I am a New York City based web developer. <br /> Currently a Web Engineer at <a target="_blank" href="http://simulmedia.com" title="Simulmedia">Simulmedia</a> and a founder of <a target="_blank" href="http://oneclicklab.com" title="OneClick Lab">OneClick Lab</a>.
url: http://sonnyt.com
permalink: /blog/:title
years: 2014 - 2017

contact:
  twitter: sonnyt
  github: sonnyt
  linkedin: in/sonnytulyaganov
  email: hi@sonnyt.com
  themeforest: sonnyt
  instagram: sonnytcom
