gems:
  - jekyll-redirect-from

title: Sonny T.
header: sonny t.
description: I am a New York City based Software Engineer. Currently a Principal Front End Engineer at <a target="_blank" href="http://simulmedia.com" title="Simulmedia">Simulmedia</a> and a founder of <a target="_blank" href="http://oneclicklab.com" title="OneClick Lab">OneClick Lab</a>.
url: http://sonnyt.com
analytics: UA-21599784-2

contact:
  twitter: sonnyt
  github: sonnyt
  linkedin: in/sonnytulyaganov
  email: hi@sonnyt.com
  themeforest: sonnyt
  instagram: sonnytcom
